services:
  - type: web
    name: symptom-classifier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn symptom_classifier_project.wsgi:application
      "
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: symptom-classifier.onrender.com
      - key: GOOGLE_API_KEY
        sync: false
