# Generated by Django 5.2.4 on 2025-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomentry',
            name='conversation_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomentry',
            name='detailed_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomentry',
            name='follow_up_questions_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomentry',
            name='initial_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
